### ISSUE TITLE
启动时卡在第一个hibernate语句无法运行

### ISSUE THREAD

**Issue by peter-gu** [zhangkaitao/es#82]
五月 09, 2015 4:38:47 下午 org.apache.tomcat.util.digester.SetPropertiesRule begin
警告: [SetPropertiesRule]{Server/Service/Engine/Host/Context} Setting property 'source' to 'org.eclipse.jst.jee.server:es-web' did not find a matching property.
五月 09, 2015 4:38:47 下午 org.apache.catalina.startup.VersionLoggerListener log
信息: Server version:        Apache Tomcat/7.0.57
五月 09, 2015 4:38:47 下午 org.apache.catalina.startup.VersionLoggerListener log
信息: Server built:          Nov 3 2014 08:39:16 UTC
五月 09, 2015 4:38:47 下午 org.apache.catalina.startup.VersionLoggerListener log
信息: Server number:         7.0.57.0
五月 09, 2015 4:38:47 下午 org.apache.catalina.startup.VersionLoggerListener log
信息: OS Name:               Windows 7
五月 09, 2015 4:38:47 下午 org.apache.catalina.startup.VersionLoggerListener log
信息: OS Version:            6.1
五月 09, 2015 4:38:47 下午 org.apache.catalina.startup.VersionLoggerListener log
信息: Architecture:          amd64
五月 09, 2015 4:38:47 下午 org.apache.catalina.startup.VersionLoggerListener log
信息: JAVA_HOME:             D:\Java\jdk1.7.0_51\jre
五月 09, 2015 4:38:47 下午 org.apache.catalina.startup.VersionLoggerListener log
信息: JVM Version:           1.7.0_51-b13
五月 09, 2015 4:38:47 下午 org.apache.catalina.startup.VersionLoggerListener log
信息: JVM Vendor:            Oracle Corporation
五月 09, 2015 4:38:47 下午 org.apache.catalina.startup.VersionLoggerListener log
信息: CATALINA_BASE:         E:\tomcat\tomcat7-9080
五月 09, 2015 4:38:47 下午 org.apache.catalina.startup.VersionLoggerListener log
信息: CATALINA_HOME:         E:\tomcat\tomcat7-9080
五月 09, 2015 4:38:47 下午 org.apache.catalina.startup.VersionLoggerListener log
信息: Command line argument: -Dcatalina.base=E:\tomcat\tomcat7-9080
五月 09, 2015 4:38:47 下午 org.apache.catalina.startup.VersionLoggerListener log
信息: Command line argument: -Dcatalina.home=E:\tomcat\tomcat7-9080
五月 09, 2015 4:38:47 下午 org.apache.catalina.startup.VersionLoggerListener log
信息: Command line argument: -Dwtp.deploy=E:\tomcat\tomcat7-9080\wtpwebapps
五月 09, 2015 4:38:47 下午 org.apache.catalina.startup.VersionLoggerListener log
信息: Command line argument: -Djava.endorsed.dirs=E:\tomcat\tomcat7-9080\endorsed
五月 09, 2015 4:38:47 下午 org.apache.catalina.startup.VersionLoggerListener log
信息: Command line argument: -Dfile.encoding=UTF-8
五月 09, 2015 4:38:47 下午 org.apache.catalina.core.AprLifecycleListener lifecycleEvent
信息: The APR based Apache Tomcat Native library which allows optimal performance in production environments was not found on the java.library.path: D:\Java\jdk1.7.0_51\bin;C:\Windows\Sun\Java\bin;C:\Windows\system32;C:\Windows;D:/Java/jdk1.7.0_51/bin/../jre/bin/server;D:/Java/jdk1.7.0_51/bin/../jre/bin;D:/Java/jdk1.7.0_51/bin/../jre/lib/amd64;D:\Oracle\product\11.1.0\db_1\bin;D:\Java\jdk1.7.0_51\bin;D:\Java\jdk1.7.0_51\jre\bin;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;D:\TortoiseSVN\bin;D:\apache-maven-3.0.5\bin;D:\UltraEdit\;D:\eclipse4.4.2;;.
五月 09, 2015 4:38:47 下午 org.apache.coyote.AbstractProtocol init
信息: Initializing ProtocolHandler ["http-bio-9080"]
五月 09, 2015 4:38:47 下午 org.apache.coyote.AbstractProtocol init
信息: Initializing ProtocolHandler ["ajp-bio-9009"]
五月 09, 2015 4:38:47 下午 org.apache.catalina.startup.Catalina load
信息: Initialization processed in 829 ms
五月 09, 2015 4:38:47 下午 org.apache.catalina.core.StandardService startInternal
信息: Starting service Catalina
五月 09, 2015 4:38:47 下午 org.apache.catalina.core.StandardEngine startInternal
信息: Starting Servlet Engine: Apache Tomcat/7.0.57
五月 09, 2015 4:38:51 下午 org.apache.catalina.startup.TaglibUriRule body
信息: TLD skipped. URI: http://java.sun.com/jstl/core_rt is already defined
五月 09, 2015 4:38:51 下午 org.apache.catalina.startup.TaglibUriRule body
信息: TLD skipped. URI: http://java.sun.com/jstl/core is already defined
五月 09, 2015 4:38:51 下午 org.apache.catalina.startup.TaglibUriRule body
信息: TLD skipped. URI: http://java.sun.com/jsp/jstl/core is already defined
五月 09, 2015 4:38:51 下午 org.apache.catalina.startup.TaglibUriRule body
信息: TLD skipped. URI: http://java.sun.com/jstl/fmt_rt is already defined
五月 09, 2015 4:38:51 下午 org.apache.catalina.startup.TaglibUriRule body
信息: TLD skipped. URI: http://java.sun.com/jstl/fmt is already defined
五月 09, 2015 4:38:51 下午 org.apache.catalina.startup.TaglibUriRule body
信息: TLD skipped. URI: http://java.sun.com/jsp/jstl/fmt is already defined
五月 09, 2015 4:38:51 下午 org.apache.catalina.startup.TaglibUriRule body
信息: TLD skipped. URI: http://java.sun.com/jsp/jstl/functions is already defined
五月 09, 2015 4:38:51 下午 org.apache.catalina.startup.TaglibUriRule body
信息: TLD skipped. URI: http://jakarta.apache.org/taglibs/standard/permittedTaglibs is already defined
五月 09, 2015 4:38:51 下午 org.apache.catalina.startup.TaglibUriRule body
信息: TLD skipped. URI: http://jakarta.apache.org/taglibs/standard/scriptfree is already defined
五月 09, 2015 4:38:51 下午 org.apache.catalina.startup.TaglibUriRule body
信息: TLD skipped. URI: http://java.sun.com/jstl/sql_rt is already defined
五月 09, 2015 4:38:51 下午 org.apache.catalina.startup.TaglibUriRule body
信息: TLD skipped. URI: http://java.sun.com/jstl/sql is already defined
五月 09, 2015 4:38:51 下午 org.apache.catalina.startup.TaglibUriRule body
信息: TLD skipped. URI: http://java.sun.com/jsp/jstl/sql is already defined
五月 09, 2015 4:38:51 下午 org.apache.catalina.startup.TaglibUriRule body
信息: TLD skipped. URI: http://java.sun.com/jstl/xml_rt is already defined
五月 09, 2015 4:38:51 下午 org.apache.catalina.startup.TaglibUriRule body
信息: TLD skipped. URI: http://java.sun.com/jstl/xml is already defined
五月 09, 2015 4:38:51 下午 org.apache.catalina.startup.TaglibUriRule body
信息: TLD skipped. URI: http://java.sun.com/jsp/jstl/xml is already defined
五月 09, 2015 4:38:51 下午 org.apache.catalina.core.ApplicationContext log
信息: No Spring WebApplicationInitializer types detected on classpath
五月 09, 2015 4:38:51 下午 org.apache.catalina.core.ApplicationContext log
信息: Initializing Spring root WebApplicationContext
五月 09, 2015 4:38:56 下午 com.alibaba.druid.pool.DruidDataSource info
信息: {dataSource-1} inited
16:39:17.350 [localhost-startStop-1] DEBUG org.apache.shiro.spring.LifecycleBeanPostProcessor - Initializing bean [userRealm]...
Hibernate: select taskdefini0_.id as id1_4_, taskdefini0_.bean_class as bean_cla2_4_, taskdefini0_.bean_name as bean_nam3_4_, taskdefini0_.cron as cron4_4_, taskdefini0_.description as descript5_4_, taskdefini0_.method_name as method_n6_4_, taskdefini0_.name as name7_4_, taskdefini0_.is_start as is_start8_4_ from maintain_task_definition taskdefini0_ where 1=1
涛哥，麻烦给看一下，都是默认配置，没有改

**Comment by Jdoing** [comment]
我也是遇到这个问题，不知道怎么解决！

**Comment by Jdoing** [comment]
把JDK版本从jdk1.7.0_79改为jdk1.7.0_17就行了

**Comment by 108851027** [comment]
我抓过dump，后台一直在做这件事情，做了好多分钟都没结束：
	  at org.springframework.core.SerializableTypeWrapper.forTypeProvider(SerializableTypeWrapper.java:148)
	  at org.springframework.core.SerializableTypeWrapper$TypeProxyInvocationHandler.invoke(SerializableTypeWrapper.java:216)
	  at com.sun.proxy.$Proxy4.getActualTypeArguments(Unknown Source:-1)
	  at sun.reflect.generics.reflectiveObjects.ParameterizedTypeImpl.equals(ParameterizedTypeImpl.java:193)
	  at sun.reflect.GeneratedMethodAccessor22.invoke(Unknown Source:-1)
	  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	  at java.lang.reflect.Method.invoke(Method.java:497)
	  at org.springframework.core.SerializableTypeWrapper$TypeProxyInvocationHandler.invoke(SerializableTypeWrapper.java:220)
	  at com.sun.proxy.$Proxy4.equals(Unknown Source:-1)
