### ISSUE TITLE
maven-db-plugin这个插件找不到

### ISSUE THREAD

**Issue by BlankKelly** [zhangkaitao/es#93]
`[INFO] ------------------------------------------------------------------------
[ERROR] No plugin found for prefix 'db' in the current project and in the plugin groups [org.mortbay.jetty, org.apache.maven.plugins, org.codehaus.mojo] available from the repositories [local (D:\mave
n\repository), oschina Releases (http://maven.oschina.net/content/groups/public), maven2-repo (http://repo1.maven.org/maven2/), Codehaus repository (http://repository.codehaus.org/), maven-db-plugin-r
epo (https://maven-db-plugin.googlecode.com/svn/maven/repo), central (http://repo.maven.apache.org/maven2)] -> [Help 1]
org.apache.maven.plugin.prefix.NoPluginFoundForPrefixException: No plugin found for prefix 'db' in the current project and in the plugin groups [org.mortbay.jetty, org.apache.maven.plugins, org.codeha
us.mojo] available from the repositories [local (D:\maven\repository), oschina Releases (http://maven.oschina.net/content/groups/public), maven2-repo (http://repo1.maven.org/maven2/), Codehaus reposit
ory (http://repository.codehaus.org/), maven-db-plugin-repo (https://maven-db-plugin.googlecode.com/svn/maven/repo), central (http://repo.maven.apache.org/maven2)]
        at org.apache.maven.plugin.prefix.internal.DefaultPluginPrefixResolver.resolve(DefaultPluginPrefixResolver.java:93)
        at org.apache.maven.lifecycle.internal.MojoDescriptorCreator.findPluginForPrefix(MojoDescriptorCreator.java:260)
        at org.apache.maven.lifecycle.internal.MojoDescriptorCreator.getMojoDescriptor(MojoDescriptorCreator.java:220)
        at org.apache.maven.lifecycle.internal.DefaultLifecycleTaskSegmentCalculator.calculateTaskSegments(DefaultLifecycleTaskSegmentCalculator.java:106)
        at org.apache.maven.lifecycle.internal.DefaultLifecycleTaskSegmentCalculator.calculateTaskSegments(DefaultLifecycleTaskSegmentCalculator.java:86)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:85)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:361)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:155)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:584)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:213)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:157)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:483)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)`

**Comment by BlankKelly** [comment]
[解决办法在这里[](url)](http://blog.csdn.net/penker_zhao/article/details/46401245)

**Comment by tour1986** [comment]
#73

**Comment by MoYanzhi** [comment]
[I write a blog about how figure out the question.](http://mistermo.iteye.com/blog/2304224)
